---
title: Prepare ENCODE ATAC/DNase Peaks 03
subtitle: Prepare the data
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project_sing.R")))
show_env()

You are working on        Singularity
BASE DIRECTORY (FD_BASE): /mount
REPO DIRECTORY (FD_REPO): /mount/repo
WORK DIRECTORY (FD_WORK): /mount/work
DATA DIRECTORY (FD_DATA): /mount/data

You are working with      ENCODE FCC
PATH OF PROJECT (FD_PRJ): /mount/repo/Proj_ENCODE_FCC
PROJECT RESULTS (FD_RES): /mount/repo/Proj_ENCODE_FCC/results
PROJECT SCRIPTS (FD_EXE): /mount/repo/Proj_ENCODE_FCC/scripts
PROJECT DATA    (FD_DAT): /mount/repo/Proj_ENCODE_FCC/data
PROJECT NOTE    (FD_NBK): /mount/repo/Proj_ENCODE_FCC/notebooks
PROJECT DOCS    (FD_DOC): /mount/repo/Proj_ENCODE_FCC/docs
PROJECT LOG     (FD_LOG): /mount/repo/Proj_ENCODE_FCC/log
PROJECT APP     (FD_APP): /mount/repo/Proj_ENCODE_FCC/app
PROJECT REF     (FD_REF): /mount/repo/Proj_ENCODE_FCC/references

**Set global variables**

In [2]:
TXT_REGION_FOLDER = "encode_open_chromatin"

## Import data

In [3]:
txt_fdiry = file.path(FD_DAT, "external")
txt_fname = "chrom.hg38.main.bed"
txt_fpath = file.path(txt_fdiry, txt_fname)

vec = c("Chrom", "ChromStart", "ChromEnd")
dat = read_tsv(txt_fpath, col_names = vec, show_col_types = FALSE)
vec = dat$Chrom

### assign and show
vec_txt_chrom = vec
print(vec)

 [1] "chr1"  "chr10" "chr11" "chr12" "chr13" "chr14" "chr15" "chr16" "chr17"
[10] "chr18" "chr19" "chr2"  "chr20" "chr21" "chr22" "chr3"  "chr4"  "chr5"
[19] "chr6"  "chr7"  "chr8"  "chr9"  "chrX"

In [4]:
### set directory
txt_folder = TXT_REGION_FOLDER
txt_fdiry  = file.path(FD_DAT, "external", txt_folder)
txt_fglob  = file.path(txt_fdiry, "*bed*")

### get file names
vec_txt_fpath = Sys.glob(txt_fglob)
vec_txt_fname = basename(vec_txt_fpath)
vec_txt_fname

[1] "K562.hg38.ENCSR000EKS.ENCFF274YGF.DNase.bed.gz"
[2] "K562.hg38.ENCSR000EOT.ENCFF185XRG.DNase.bed.gz"
[3] "K562.hg38.ENCSR483RKN.ENCFF558BLC.ATAC.bed.gz"
[4] "K562.hg38.ENCSR483RKN.ENCFF925CYR.ATAC.bed.gz"
[5] "K562.hg38.ENCSR868FGK.ENCFF333TAT.ATAC.bed.gz"
[6] "K562.hg38.ENCSR868FGK.ENCFF948AFM.ATAC.bed.gz"

In [5]:
lst = lapply(vec_txt_fpath, function(txt_fpath){
    dat = read_tsv(txt_fpath, col_names = FALSE, show_col_types = FALSE)
    return(dat)
})
names(lst) = vec_txt_fname

lst_dat_import = lst

In [6]:
lst = lst_dat_import
lst = lapply(lst, function(dat){
    dat = dat %>% 
        dplyr::filter(X1 %in% vec_txt_chrom) %>%
        dplyr::arrange(X1, X2, X3)
    return(dat)
})

lst_dat_arrange = lst

**Check**

In [7]:
lst = lst_dat_import
dat = lst[[4]]
head(dat)

  X1    X2        X3        X4 X5   X6 X7       X8       X9       X10
1 chr9  131124809 131126067 .  1000 .  22.41632 4381.931 4375.260 657
2 chr22  21641476  21642667 .  1000 .  13.33761 3766.814 3760.284 685
3 chr9  120868424 120869438 .  1000 .  22.14111 3623.660 3617.170 376
4 chr22  21735419  21736448 .  1000 .  16.63537 3321.324 3314.979 592
5 chr22  20916753  20918326 .  1000 .  18.65871 3288.512 3282.194 550
6 chr22  21735419  21736448 .  1000 .  16.51002 3287.637 3281.319 462

In [8]:
lst = lst_dat_arrange
dat = lst[[4]]
head(dat)

  X1   X2     X3     X4 X5   X6 X7       X8        X9        X10
1 chr1 778328 779235 .  1000 .  28.93443 749.94922 745.95093 458
2 chr1 778328 779235 .  1000 .   3.36066  20.42077  18.19629 788
3 chr1 778328 779235 .  1000 .   2.37705   8.90270   6.89830  74
4 chr1 817237 818202 .  1000 .   8.38235  66.38497  63.80160 275
5 chr1 817237 818202 .  1000 .   3.53618  12.45234  10.35933 844
6 chr1 817237 818202 .  1000 .   2.88577   8.24392   6.26027 608

**Check**

In [9]:
lst = lst_dat_import
lst = lapply(lst, function(dat){
    res = as.data.frame(table(dat$X1))
    return(res)
})
dat = bind_rows(lst, .id = "Files")
colnames(dat) = c("Files", "Chrom", "Count")
dat = dat %>% tidyr::spread(Chrom, Count)
fun_display_table(dat)

Files,chr1,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr2,chr20,chr21,chr22,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chrX,chrY
K562.hg38.ENCSR000EKS.ENCFF274YGF.DNase.bed.gz,12452,5480,6329,5905,2413,3398,3709,4493,5956,2033,6342,8434,3357,1242,3344,7095,4480,5670,7056,6435,4697,4841,3556,4
K562.hg38.ENCSR000EOT.ENCFF185XRG.DNase.bed.gz,16479,7168,8275,8022,3328,4571,5169,5866,7538,2949,7454,11748,4323,1963,3440,9776,6871,7880,10071,8551,6665,6128,5035,7
K562.hg38.ENCSR483RKN.ENCFF558BLC.ATAC.bed.gz,24045,8911,10864,9419,3136,4995,6505,7541,9093,3116,8742,15925,5105,2587,4626,12141,8285,9911,14090,13583,8281,7615,5355,3
K562.hg38.ENCSR483RKN.ENCFF925CYR.ATAC.bed.gz,14206,5420,6921,5747,1827,3201,3939,4872,6284,1728,6555,8955,3192,1409,2973,7064,4527,5819,8163,7361,4815,4691,3340,NA
K562.hg38.ENCSR868FGK.ENCFF333TAT.ATAC.bed.gz,31171,11955,13646,12532,4681,6836,8649,9019,11224,5082,10188,21514,6352,3904,5915,16450,11960,13616,18863,18102,11265,9779,7089,8
K562.hg38.ENCSR868FGK.ENCFF948AFM.ATAC.bed.gz,20798,7978,9620,8606,3045,4780,5858,6430,8298,3046,8081,13707,4452,2407,4195,10787,7534,8827,12403,11335,7369,6747,5033,4

In [10]:
lst = lst_dat_arrange
lst = lapply(lst, function(dat){
    res = as.data.frame(table(dat$X1))
    return(res)
})
dat = bind_rows(lst, .id = "Files")
colnames(dat) = c("Files", "Chrom", "Count")
dat = dat %>% tidyr::spread(Chrom, Count)
fun_display_table(dat)

Files,chr1,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr2,chr20,chr21,chr22,chr3,chr4,chr5,chr6,chr7,chr8,chr9,chrX
K562.hg38.ENCSR000EKS.ENCFF274YGF.DNase.bed.gz,12452,5480,6329,5905,2413,3398,3709,4493,5956,2033,6342,8434,3357,1242,3344,7095,4480,5670,7056,6435,4697,4841,3556
K562.hg38.ENCSR000EOT.ENCFF185XRG.DNase.bed.gz,16479,7168,8275,8022,3328,4571,5169,5866,7538,2949,7454,11748,4323,1963,3440,9776,6871,7880,10071,8551,6665,6128,5035
K562.hg38.ENCSR483RKN.ENCFF558BLC.ATAC.bed.gz,24045,8911,10864,9419,3136,4995,6505,7541,9093,3116,8742,15925,5105,2587,4626,12141,8285,9911,14090,13583,8281,7615,5355
K562.hg38.ENCSR483RKN.ENCFF925CYR.ATAC.bed.gz,14206,5420,6921,5747,1827,3201,3939,4872,6284,1728,6555,8955,3192,1409,2973,7064,4527,5819,8163,7361,4815,4691,3340
K562.hg38.ENCSR868FGK.ENCFF333TAT.ATAC.bed.gz,31171,11955,13646,12532,4681,6836,8649,9019,11224,5082,10188,21514,6352,3904,5915,16450,11960,13616,18863,18102,11265,9779,7089
K562.hg38.ENCSR868FGK.ENCFF948AFM.ATAC.bed.gz,20798,7978,9620,8606,3045,4780,5858,6430,8298,3046,8081,13707,4452,2407,4195,10787,7534,8827,12403,11335,7369,6747,5033

## Save results

In [11]:
### set file path
txt_folder = TXT_REGION_FOLDER
txt_fdiry  = file.path(FD_RES, "region", txt_folder)
dir.create(txt_fdiry, showWarnings = FALSE)

lst = lst_dat_arrange
for (txt_fname in names(lst)){
    txt_fpath = file.path(txt_fdiry, txt_fname)
    
    dat = lst[[txt_fname]]
    write_tsv(dat, txt_fpath, col_names = FALSE)
    
    print(txt_fname)
}

[1] "K562.hg38.ENCSR000EKS.ENCFF274YGF.DNase.bed.gz"
[1] "K562.hg38.ENCSR000EOT.ENCFF185XRG.DNase.bed.gz"
[1] "K562.hg38.ENCSR483RKN.ENCFF558BLC.ATAC.bed.gz"
[1] "K562.hg38.ENCSR483RKN.ENCFF925CYR.ATAC.bed.gz"
[1] "K562.hg38.ENCSR868FGK.ENCFF333TAT.ATAC.bed.gz"
[1] "K562.hg38.ENCSR868FGK.ENCFF948AFM.ATAC.bed.gz"