**Set environment**

In [1]:
suppressWarnings(suppressMessages(source("../config/config_sing.R")))
show_env()

You are in Singularity: singularity_proj_encode_fcc
BASE DIRECTORY (FD_BASE): /data/reddylab/Kuei
WORK DIRECTORY (FD_WORK): /data/reddylab/Kuei/out
CODE DIRECTORY (FD_CODE): /data/reddylab/Kuei/code
PATH OF PROJECT (FD_PRJ): /data/reddylab/Kuei/code/Proj_CombEffect_ENCODE_FCC
PATH OF RESULTS (FD_RES): /data/reddylab/Kuei/out/proj_combeffect_encode_fcc
PATH OF LOG     (FD_LOG): /data/reddylab/Kuei/out/proj_combeffect_encode_fcc/log

**Check data**

In [2]:
fdiry = file.path(
    FD_RES,
    "source",
    "annotation_enhancer_junke")
dir(fdiry)

[1] "ATAC_STARR_deep"  "WHG_STARR_seq_TR"

In [3]:
fdiry = file.path(
    FD_RES,
    "source",
    "annotation_enhancer_junke",
    "ATAC_STARR_deep",
    "deep_ATAC_STARR_seq.full_overlap_100bp_bin_10bp_stepSize",
    "processed",
    "merged_peak"
)
for (x in dir(fdiry)) {cat(x, "\n")}

merged_sig_down_in_each_orientation.bed.gz
merged_sig_up_in_each_orientation.bed.gz
orientation_independent_up_regulated_peaks_intersection.bed.gz
orientation_independent_up_regulated_peaks_union.bed.gz
size_constrained_merged_sig_down_in_each_orientation.bed.gz
size_constrained_merged_sig_up_in_each_orientation.bed.gz
size_constrained_orientation_independent_up_regulated_peaks_intersection.bed.gz
size_constrained_orientation_independent_up_regulated_peaks_union.bed.gz

## Import data

**ASTARR**

In [4]:
ASSAY="ATAC_STARR_deep"
FOLDER="deep_ATAC_STARR_seq.full_overlap_100bp_bin_10bp_stepSize"
FN_INP="orientation_independent_up_regulated_peaks_union.bed.gz"

### set file path
### FP_INP=${FD_INP}/${ASSAY}/${FOLDER}/processed/merged_peak/${FN_INP}
fdiry = file.path(
    FD_RES,
    "source",
    "annotation_enhancer_junke",
    ASSAY,
    FOLDER,
    "processed",
    "merged_peak"
)
fname = FN_INP
fpath = file.path(fdiry, fname)

cnames = c(
    "Chrom",
    "Start",
    "End",
    "Score",
    "Score_across_all_the_bins",
    "Size"
)
dat = read_tsv(fpath, col_names = cnames)

dat_peak_astarr_import = dat
print(dim(dat))
head(dat, 3)

Rows: 22991 Columns: 6
── Column specification ─────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): Chrom, Score_across_all_the_bins
dbl (4): Start, End, Score, Size

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 22991     6

  Chrom Start  End    Score
1 chr1  115570 115740 1.506972
2 chr1  605280 605470 1.616298
3 chr1  778370 778900 1.517446
  Score_across_all_the_bins
1 1.78537590036678,1.63140988407361,1.70749355744947,1.51371448138556,1.88193982340175,1.38498851833212,1.83472080382451,1.27592154305467,1.81206137027028,1.06273283777018,1.79759191426686,1.03524596411935,1.38517729102636,1.40460508911999,1.53009789412319,1.06846720586669
2 1.62987658442724,1.649266499375,1.69101981990541,1.56802042791103,1.54330778171409
3 1.56947903117621,1.02258698959509,1.20233423998739,1.27499911363028,1.32548646452119,1.26385481523464,1.23000704748212,1.57404483698418,1.1695373413352,1.53837789500309,1.14448555278569,1.53055001335118,1.07509931914851,1.51113652781492,1.0335223642164,1.50079476402205,1.03571786751961,1.50077720749375,1.02923183719275,1.50430260231385,1.03936340640705,1.49591228704888,1.68740279348032,1.68260729857832,1.03981750540242,1.58173895079377,1.13294163882877,1.52137193706437,1.11921353751676,1.54066697437559,1.253966363493,1.61129060721554,1.25386324732641,1.60350000281797,1.16960231174401,1.60195968131727,1.16609991936202,1.52677915119061,1.04147168440602,1.17766693986879,1.1490027365734,1.07552368615834,1.18796322761306,1.08784718645857,1.21409010804907,1.11722604574841,1.20307509679482,1.08695426718269,1.33195140209331,1.18100947738155,1.21913675916686,1.29537493115311,1.46396317843156,1.19780467094242,1.48751450949652,2.17863540203214,1.71351248688845,2.21066377643389,1.69396588401873,2.2328285571516,1.71533477712471,2.25631329968567,1.75754703851587,2.28332206154309,1.78960312623592,2.30578532796446,1.78891021333073,2.36552375034284,1.76751047706554,2.46360232802009,1.72503846818595,2.03489759653111,1.96015682513023,1.98569442094665,1.89080129523387,1.33486692923808,2.12249118706231,1.26074497467326,2.06586089935725,1.96229726307002,1.97591241724924,2.00676363383199
  Size
1 170
2 190
3 530

**WSTARR**

In [5]:
ASSAY="WHG_STARR_seq_TR"
FOLDER="WHG_STARR_seq_TR.full_overlap_100_bp_bin_10_bp_stepSize"
FN_INP="orientation_independent_up_regulated_peaks_union.bed.gz"

### set file path
### FP_INP=${FD_INP}/${ASSAY}/${FOLDER}/processed/merged_peak/${FN_INP}
fdiry = file.path(
    FD_RES,
    "source",
    "annotation_enhancer_junke",
    ASSAY,
    FOLDER,
    "processed",
    "merged_peak"
)
fname = FN_INP
fpath = file.path(fdiry, fname)

cnames = c(
    "Chrom",
    "Start",
    "End",
    "Score",
    "Score_across_all_the_bins",
    "Size"
)
dat = read_tsv(fpath, col_names = cnames)

dat_peak_wstarr_import = dat
print(dim(dat))
head(dat, 3)

Rows: 45596 Columns: 6
── Column specification ─────────────────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): Chrom, Score_across_all_the_bins
dbl (4): Start, End, Score, Size

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

[1] 45596     6

  Chrom Start  End    Score
1 chr1  778420 779100 1.655814
2 chr1  827490 827570 1.168009
3 chr1  827670 827740 1.022223
  Score_across_all_the_bins
1 1.22779520901764,1.06370701900437,1.1800089207526,1.25068739119878,1.23953664533542,1.00448603210723,1.31453544687431,1.06455846384185,1.3407284726994,1.42854414727248,1.12235405708707,1.47482892940696,1.21096762591592,1.53909444692536,1.29764576552236,1.57986667787679,1.38251099935478,1.72501606014559,1.50024426862898,1.70013390168204,1.57399415344729,1.83327513383231,1.58383752899849,1.86901717059401,1.72760513215623,1.88356046420319,1.84770314277034,1.86025584645276,1.86451367790412,1.92942465379874,1.94229433296564,1.96148265236793,2.02298300303287,2.03490091593825,2.17624307148932,2.04710838092234,2.17208349397162,2.20020936973993,2.29904338671565,2.06560225789253,2.28634597209995,1.98376407483848,2.32285791534701,2.02308928587429,2.36876244159905,2.00874157475221,2.43162890344175,1.97547604308549,2.47382401897508,2.02193829598185,2.51146987508955,2.11579042560784,2.40128926891045,1.90270448508902,2.31294501567822,1.8898417363367,2.36818004862654,1.83873634454979,2.27095684159175,1.69526951263065,2.12107298553835,1.64546655157565,2.06662919457071,1.63133701232061,1.98888137445066,1.70218318186691,2.02647228481749,1.69085769960792,1.98587302112118,1.69095141294559,2.01731841456915,1.58805002679841,1.86278040886703,1.57055903327303,1.84371060876115,1.50459409386453,1.72817075363473,1.52829983145996,1.61240334126644,1.57081741374424,1.57780490332567,1.42496898353044,1.50918856326203,1.37841154650453,1.46712405111515,1.37309209171356,1.41649396987121,1.41245926296661,1.40997485014694,1.33507688180998,1.35657947561759,1.27096630015919,1.35807071326865,1.23631802582872,1.31607298937239,1.2324998252981,1.33897648922669,1.21152556070507,1.28456363934681,1.20590761752204,1.19399202951494,1.13615030412566,1.1834372687982,1.07749625279643,1.16980319857778,1.00256278084047,1.18238135834922,1.20285872552545,1.16449421133399,1.12498022179486,1.11864138241867
2 1.0577633274366,1.27825420441784
3 1.01790694179397,1.02653834474655
  Size
1 680
2  80
3  70

## Check

**ASTARR**

In [6]:
dat = dat_peak_astarr_import
dat = dat %>% 
    dplyr::select(Score, Score_across_all_the_bins) %>%
    head %>%
    dplyr::rowwise() %>%
    dplyr::mutate(Mean = mean(as.double(unlist(str_split(Score_across_all_the_bins, ","))))) %>%
    dplyr::select(-Score_across_all_the_bins)
dat

  Score    Mean
1 1.506972 1.506972
2 1.616298 1.616298
3 1.517446 1.517446
4 1.341718 1.341718
5 1.081725 1.081725
6 1.160732 1.160732

In [7]:
dat = dat_peak_astarr_import
dat = dat %>% 
    dplyr::select(Start, End, Size) %>%
    head %>%
    dplyr::mutate(Length = End - Start)
dat

  Start  End    Size Length
1 115570 115740 170  170
2 605280 605470 190  190
3 778370 778900 530  530
4 827450 827550 100  100
5 944320 944500 180  180
6 967240 967410 170  170

**WSTARR**

In [8]:
dat = dat_peak_wstarr_import
dat = dat %>% 
    dplyr::select(Score, Score_across_all_the_bins) %>%
    head %>%
    dplyr::rowwise() %>%
    dplyr::mutate(Mean = mean(as.double(unlist(str_split(Score_across_all_the_bins, ","))))) %>%
    dplyr::select(-Score_across_all_the_bins)
dat

  Score    Mean
1 1.655814 1.655814
2 1.168009 1.168009
3 1.022223 1.022223
4 1.085300 1.085300
5 1.036642 1.036642
6 1.037478 1.037478

In [9]:
dat = dat_peak_wstarr_import
dat = dat %>% 
    dplyr::select(Start, End, Size) %>%
    head %>%
    dplyr::mutate(Length = End - Start)
dat

  Start  End    Size Length
1 778420 779100 680  680
2 827490 827570  80   80
3 827670 827740  70   70
4 844100 844200 100  100
5 913190 913280  90   90
6 921020 921320 300  300

## Arrange

In [10]:
dat = dat_peak_astarr_import
dat = dat %>% dplyr::select(-Score_across_all_the_bins, -Size)

dat_peak_astarr = dat
print(dim(dat))
head(dat)

[1] 22991     4

  Chrom Start  End    Score
1 chr1  115570 115740 1.506972
2 chr1  605280 605470 1.616298
3 chr1  778370 778900 1.517446
4 chr1  827450 827550 1.341718
5 chr1  944320 944500 1.081725
6 chr1  967240 967410 1.160732

In [11]:
dat = dat_peak_wstarr_import
dat = dat %>% dplyr::select(-Score_across_all_the_bins, -Size)

dat_peak_wstarr = dat
print(dim(dat))
head(dat)

[1] 45596     4

  Chrom Start  End    Score
1 chr1  778420 779100 1.655814
2 chr1  827490 827570 1.168009
3 chr1  827670 827740 1.022223
4 chr1  844100 844200 1.085300
5 chr1  913190 913280 1.036642
6 chr1  921020 921320 1.037478

## Data dictionary

In [12]:
dat_cnames = data.frame(
    Name = c(            
        "Chrom",          
        "Start",
        "End",
        "Score"
    ),
    Description = c(
        "Seqnames",
        "Start",
        "End",
        "Activity"
    )
)

dat_cnames

  Name  Description
1 Chrom Seqnames
2 Start Start
3 End   End
4 Score Activity

## Save results

In [13]:
fdiry = file.path(FD_RES, "results", "region", "annotation_enhancer_junke")
fname = "enhancer_junke_peak_astarr.bed.gz"
fpath = file.path(fdiry, fname)

dat = dat_peak_astarr
write_tsv(dat, fpath, col_names = FALSE)

In [14]:
fdiry = file.path(FD_RES, "results", "region", "annotation_enhancer_junke")
fname = "enhancer_junke_peak_wstarr.bed.gz"
fpath = file.path(fdiry, fname)

dat = dat_peak_wstarr
write_tsv(dat, fpath, col_names = FALSE)

In [15]:
fdiry = file.path(FD_RES, "results", "region", "annotation_enhancer_junke")
fname = "description.tsv"
fpath = file.path(fdiry, fname)

dat = dat_cnames
write_tsv(dat, fpath)