---
title: Region Coverage 12
subtitle: Combine counts across samples and generate count matrix (Tiling-MPRA)
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project_sing.R")))
show_env()

You are working on        Singularity: singularity_proj_encode_fcc
BASE DIRECTORY (FD_BASE): /data/reddylab/Kuei
REPO DIRECTORY (FD_REPO): /data/reddylab/Kuei/repo
WORK DIRECTORY (FD_WORK): /data/reddylab/Kuei/work
DATA DIRECTORY (FD_DATA): /data/reddylab/Kuei/data

You are working with      ENCODE FCC
PATH OF PROJECT (FD_PRJ): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC
PROJECT RESULTS (FD_RES): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results
PROJECT SCRIPTS (FD_EXE): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/scripts
PROJECT DATA    (FD_DAT): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/data
PROJECT NOTE    (FD_NBK): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/notebooks
PROJECT DOCS    (FD_DOC): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/docs
PROJECT LOG     (FD_LOG): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/log
PROJECT REF     (FD_REF): /data/reddylab/Kuei/repo/Proj_ENCODE_FCC/references

In [2]:
txt_fdiry = file.path(FD_RES, "assay_fcc")
vec = dir(txt_fdiry)
for (txt in vec) {cat(txt, "\n")}

CRISPRi_FlowFISH_K562_Riley_JinWoo
CRISPRi_Growth_K562_Gersbach_JinWoo
MPRA_Lenti_K562_Nadav_Vikram
MPRA_Tiling_K562_Tewhey_Hannah
STARR_ATAC_K562_Reddy_KS274
STARR_ATAC_K562_Reddy_KS91
STARR_ATAC_K562_Reddy_KSMerge
STARR_WHG_K562_Reddy_A001

## Import region data

**Read region metadata table**

In [3]:
### set directory
txt_fdiry = file.path(FD_RES, "region", "summary")
txt_fname = "metadata.label.region_for_analysis.tsv"
txt_fpath = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### assign and show
dat_meta_region = dat
fun_display_table(dat)

Folder,FName,Label,FPath
region_for_analysis,K562.hg38.ASTARR.macs.KS91.input.rep_all.max_overlaps.q5.bed.gz,fcc_astarr_macs_input_overlap,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ASTARR.macs.KS91.input.rep_all.max_overlaps.q5.bed.gz
region_for_analysis,K562.hg38.ASTARR.macs.KS91.input.rep_all.union.q5.bed.gz,fcc_astarr_macs_input_union,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ASTARR.macs.KS91.input.rep_all.union.q5.bed.gz
region_for_analysis,K562.hg38.ENCSR000EKS.ENCFF274YGF.DNase.bed.gz,dnase_ENCFF274YGF,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ENCSR000EKS.ENCFF274YGF.DNase.bed.gz
region_for_analysis,K562.hg38.ENCSR000EOT.ENCFF185XRG.DNase.bed.gz,dnase_ENCFF185XRG,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ENCSR000EOT.ENCFF185XRG.DNase.bed.gz
region_for_analysis,K562.hg38.ENCSR483RKN.ENCFF558BLC.ATAC.bed.gz,atac_ENCFF558BLC,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ENCSR483RKN.ENCFF558BLC.ATAC.bed.gz
region_for_analysis,K562.hg38.ENCSR483RKN.ENCFF925CYR.ATAC.bed.gz,atac_ENCFF925CYR,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ENCSR483RKN.ENCFF925CYR.ATAC.bed.gz
region_for_analysis,K562.hg38.ENCSR868FGK.ENCFF333TAT.ATAC.bed.gz,atac_ENCFF333TAT,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ENCSR868FGK.ENCFF333TAT.ATAC.bed.gz
region_for_analysis,K562.hg38.ENCSR868FGK.ENCFF948AFM.ATAC.bed.gz,atac_ENCFF948AFM,/data/reddylab/Kuei/repo/Proj_ENCODE_FCC/results/region/region_for_analysis/K562.hg38.ENCSR868FGK.ENCFF948AFM.ATAC.bed.gz

**Create region list for looping**

In [4]:
dat = dat_meta_region
lst = split(dat$Folder, dat$Label)

lst_txt_region = lst
print(lst)

$atac_ENCFF333TAT
[1] "region_for_analysis"

$atac_ENCFF558BLC
[1] "region_for_analysis"

$atac_ENCFF925CYR
[1] "region_for_analysis"

$atac_ENCFF948AFM
[1] "region_for_analysis"

$dnase_ENCFF185XRG
[1] "region_for_analysis"

$dnase_ENCFF274YGF
[1] "region_for_analysis"

$fcc_astarr_macs_input_overlap
[1] "region_for_analysis"

$fcc_astarr_macs_input_union
[1] "region_for_analysis"

## Loop through regions and assays to create count matrix

**Test loop**

In [5]:
### init: region folders
dat = dat_meta_region
vec = dat$Label
vec_txt_region = vec

### init: assay
txt_assay      = "MPRA_Tiling_K562_Tewhey_Hannah"
vec_txt_prefix = c("OL13", "OL43", "OL45")
vec_txt_type   = c("raw", "norm")

### execute
for (txt_region_label in vec_txt_region[1]) {

    ### set directory for region description
    txt_region_folder = lst_txt_region[[txt_region_label]]
    txt_fdiry = file.path(FD_RES, "region", txt_region_folder, "summary")
    txt_fname = "description.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)

    ### get region description and set column names/types
    dat = read_tsv(txt_fpath, show_col_types = FALSE)
    vec = dat$Name
    vec_txt_cname = c(vec, "Count")
    vec_col_ctype = cols(Count = col_character())
    
    ### loop through each assay under each region
    for (txt_prefix in vec_txt_prefix) {
        for (txt_type in vec_txt_type) {
            ### set directory for assay metadata
            txt_fdiry = file.path(FD_RES, "assay_fcc", txt_assay, "fragment_counts", "summary")
            txt_fname = "metadata.tsv"
            txt_fpath = file.path(txt_fdiry, txt_fname)
        
            ### read metadata and setup sample names
            dat  = read_tsv(txt_fpath, show_col_types = FALSE)
            vec1 = dat$FName
            vec2 = dat$Sample
            dat_meta_assay = dat
            vec_txt_sample = setNames(vec1, vec2)
            
            ### set directory for assay counts
            txt_fdiry = file.path(
                FD_RES, "region_coverage_fcc",
                txt_region_label,
                txt_assay,
                "overlap_count"
            )
            txt_fname = paste("", txt_prefix, "hg38", txt_type, "bed.gz", sep = "*")
            txt_fglob = file.path(txt_fdiry, txt_fname)

            ### get count files
            vec_txt_fpath = Sys.glob(txt_fglob)
            vec_txt_fname = basename(vec_txt_fpath)

            ### show progress:
            cat("\n====================\n")
            cat("Region Folder:", txt_region_folder, "\n")
            cat("Region Label: ", txt_region_label,  "\n")
            cat("Assay  Folder:", txt_assay,         "\n")
            cat("Import Counts:\n")
            print(vec_txt_fname)
            cat("\n")
            flush.console()
        }
    }
}

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"


====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"


====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"


====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"


====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"


====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

**Define helper function**

In [6]:
fun = function(dat1, dat2){
    dat = dplyr::full_join(dat1, dat2, by = c("Chrom", "ChromStart", "ChromEnd", "Region"))
    return(dat)
}

**Generate count matrix for each region set for each assay**

In [8]:
### init: region folders
dat = dat_meta_region
vec = dat$Label
vec_txt_region = vec

### init: assay
txt_assay      = "MPRA_Tiling_K562_Tewhey_Hannah"
vec_txt_prefix = c("OL13", "OL43", "OL45")
vec_txt_type   = c("raw", "norm")

### loop
for (txt_region_label in vec_txt_region) {
    
    ### set directory for region description
    txt_region_folder = lst_txt_region[[txt_region_label]]
    txt_fdiry = file.path(FD_RES, "region", txt_region_folder, "summary")
    txt_fname = "description.tsv"
    txt_fpath = file.path(txt_fdiry, txt_fname)

    ### get region description and set column names/types
    dat = read_tsv(txt_fpath, show_col_types = FALSE)
    vec = dat$Name
    vec_txt_cname = c(vec, "Count")
    vec_col_ctype = cols(Count = col_character())
        
    ### loop through each assay under each region
    for (txt_prefix in vec_txt_prefix) {
        for (txt_type in vec_txt_type) {
            
            ### set directory for assay metadata
            txt_fdiry = file.path(FD_RES, "assay_fcc", txt_assay, "fragment_counts", "summary")
            txt_fname = "metadata.tsv"
            txt_fpath = file.path(txt_fdiry, txt_fname)
        
            ### read metadata and setup sample names
            dat  = read_tsv(txt_fpath, show_col_types = FALSE)
            vec1 = dat$FName
            vec2 = dat$Sample
            dat_meta_assay = dat
            vec_txt_sample = setNames(vec1, vec2)
            
            ### set directory for assay counts
            txt_fdiry = file.path(
                FD_RES, "region_coverage_fcc",
                txt_region_label,
                txt_assay,
                "overlap_count"
            )
            txt_fname = paste("", txt_prefix, "hg38", txt_type, "bed.gz", sep = "*")
            txt_fglob = file.path(txt_fdiry, txt_fname)

            ### get count files
            vec_txt_fpath = Sys.glob(txt_fglob)
            vec_txt_fname = basename(vec_txt_fpath)

            ### show progress:
            cat("\n====================\n")
            cat("Region Folder:", txt_region_folder, "\n")
            cat("Region Label: ", txt_region_label,  "\n")
            cat("Assay  Folder:", txt_assay,         "\n")
            cat("Import Counts:\n")
            print(vec_txt_fname)
            cat("\n")
            flush.console()

            ### loop through count files and import them
            lst_dat = lapply(vec_txt_fpath, function(txt_fpath){

                ### read table
                dat = read_tsv(
                    txt_fpath, 
                    col_names = vec_txt_cname, 
                    col_types = vec_col_ctype, 
                    show_col_types = FALSE)
    
                ### arrange the columns
                dat = dat %>% 
                    dplyr::select(Chrom, ChromStart, ChromEnd, Count) %>%
                    dplyr::mutate(Region = paste0(Chrom, ":", ChromStart, "-", ChromEnd)) %>%
                    dplyr::mutate(Count  = replace(Count, Count == ".", "0")) %>%
                    dplyr::mutate(Count  = as.integer(Count)) %>%
                    dplyr::select(Chrom, ChromStart, ChromEnd, Region, Count) %>%
                    dplyr::distinct()
    
                ### rename column to include the file name
                txt_fname = basename(txt_fpath)
                vec = c("Chrom", "ChromStart", "ChromEnd", "Region", txt_fname)
                colnames(dat) = vec
                
                return(dat)
            })
            
            ### combine imported counts into a matrix
            dat_cnt = Reduce(fun, lst_dat)
            dat_cnt = dplyr::rename(dat_cnt, any_of(vec_txt_sample))
            
            ### filter out unaligned reigons
            mat_cnt = dat_cnt %>%
                dplyr::select(-Chrom, -ChromStart, -ChromEnd) %>%
                column_to_rownames(var = "Region")
            vec  = apply(mat_cnt, 1, sum)
            idx1 = (vec != 0)
            
            ### re-order columns: Input ---> Output
            vec  = colnames(mat_cnt)
            vec  = sort(vec)
            idx2 = c("Chrom", "ChromStart", "ChromEnd", "Region", vec)
            
            ### get the final count matrix
            dat_cnt = dat_cnt[idx1,idx2]
    
            ### combine count matrix and column data
            dat_col = dat_meta_assay %>% dplyr::filter(FName %in% vec_txt_fname)
            lst_dat = list(
                "data_cnt" = dat_cnt,
                "data_col" = dat_col
            )

            ### show progress
            cat("Removing zero:", "\n")
            cat("Before removing zero:", nrow(mat_cnt), "\n")
            cat("After  removing zero:", nrow(dat_cnt), "\n")
            cat("\n")
            flush.console()

            ### show progress
            cat("Save count matrix and data list.\n")
            flush.console()
            
            ### set directory for saving results
            txt_fdiry = file.path(
                FD_RES, "region_coverage_fcc",
                txt_region_label,
                txt_assay,
                "overlap_count",
                "summary"
            )
            txt_cmd = paste("mkdir -p", txt_fdiry)
            system(txt_cmd)
    
            ### save count matrix
            ###     matrix.count.raw.OL13.tsv
            ###     matrix.count.raw.OL43.tsv
            ###     matrix.count.raw.OL45.tsv
            #txt_fname = "matrix.raw.count.WGS.tsv"
            txt_fname = paste("matrix", "count", txt_type, txt_prefix, "tsv", sep = ".")
            txt_fpath = file.path(txt_fdiry, txt_fname)
            cat(txt_fname, "\n")
            flush.console()
            
            dat = dat_cnt
            write_tsv(dat, txt_fpath)
    
            ### save data list
            ###     data_list.count_column.raw.OL13.tsv
            ###     data_list.count_column.raw.OL43.tsv
            #txt_fname = "data_list_count_column.rds"
            txt_fname = paste("data", "count_column", txt_type, txt_prefix, "rds", sep = ".")
            txt_fpath = file.path(txt_fdiry, txt_fname)
            cat(txt_fname, "\n")
            flush.console()
            
            obj = lst_dat
            saveRDS(obj, txt_fpath)
    
            ### show progress: matrix
            cat("\n")
            cat("First few rows of the matrix:", "\n")
            flush.console()
            fun_display_table(head(dat_cnt, 3))
            
            cat("Last few rows of the matrix:", "\n")
            flush.console()
            fun_display_table(tail(dat_cnt, 3))
            cat("\n")
            flush.console()
        }
    }
}

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 150042
After  removing zero: 18

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792073,61793400,chr11:61792073-61793400,115231,64459,105630,66537,459419,460044,685058,605858
chr11,61800349,61801103,chr11:61800349-61801103,51623,29866,46786,30377,387545,363598,532432,432382
chr11,61806747,61807139,chr11:61806747-61807139,59913,32102,51661,33375,24416,22960,39884,41587

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61884984,61885688,chr11:61884984-61885688,84219,46084,73750,46349,40159,36762,61062,65233
chr11,61890533,61892307,chr11:61890533-61892307,107564,59361,95984,62572,243844,231725,340691,336004
chr11,61897750,61898277,chr11:61897750-61898277,60664,33854,54776,34456,43452,43631,61233,75918

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 150042
After  removing zero: 18

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792073,61793400,chr11:61792073-61793400,63155,63160,64734,64613,982964,926013,871807,739832
chr11,61800349,61801103,chr11:61800349-61801103,28293,29264,28672,29498,829184,731878,677575,527995
chr11,61806747,61807139,chr11:61806747-61807139,32836,31455,31660,32409,52240,46215,50756,50783

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61884984,61885688,chr11:61884984-61885688,46158,45155,45197,45008,85923,73997,77707,79658
chr11,61890533,61892307,chr11:61890533-61892307,58953,58164,58823,60762,521724,466434,433564,410305
chr11,61897750,61898277,chr11:61897750-61898277,33248,33171,33569,33459,92969,87823,77925,92705

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 150042
After  removing zero: 307

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126778958,126779697,chr8:126778958-126779697,8547,9460,8862,9084,4489,4635,37417,23039,53418,39611,43072
chr8,126804911,126805784,chr8:126804911-126805784,11911,13604,12871,12822,6179,6182,62531,42004,71537,54242,62156
chr8,126817058,126817474,chr8:126817058-126817474,9464,10833,10041,10373,4861,4787,7776,6111,10299,6917,7791

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862162,49862722,chrX:49862162-49862722,5540,6512,5865,5650,2870,2914,69580,38103,87608,67444,74226
chrX,49868330,49869060,chrX:49868330-49869060,15518,17861,16412,16743,8058,7889,20407,14271,25973,18157,20473
chrX,49878433,49880072,chrX:49878433-49880072,12038,13523,13008,12966,6213,6238,147827,103517,165148,131406,139284

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 150042
After  removing zero: 307

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126778958,126779697,chr8:126778958-126779697,5754,5638,5680,5708,5853,6030,58042,41175,57656,68303,60856
chr8,126804911,126805784,chr8:126804911-126805784,8020,8108,8250,8057,8057,8043,97000,75070,77213,93532,87820
chr8,126817058,126817474,chr8:126817058-126817474,6372,6456,6436,6518,6338,6228,12062,10921,11116,11927,11007

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862162,49862722,chrX:49862162-49862722,3730,3881,3759,3550,3742,3791,107935,68098,94559,116297,104874
chrX,49868330,49869060,chrX:49868330-49869060,10448,10645,10520,10521,10507,10264,31656,25505,28033,31309,28926
chrX,49878433,49880072,chrX:49878433-49880072,8105,8059,8338,8147,8101,8116,229316,185006,178252,226590,196795

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 150042
After  removing zero: 823

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4551522,4551988,chr11:4551522-4551988,3131,2651,2775,2506,4978,3767,3508,5938
chr11,4554256,4554817,chr11:4554256-4554817,3648,2881,2955,3139,26407,27823,29110,26936
chr11,4577505,4578002,chr11:4577505-4578002,3491,3078,3287,3079,3239,2785,2608,3223

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58371839,58372138,chr20:58371839-58372138,2280,1781,2001,1910,1874,1363,1151,2101
chr20,58373731,58374925,chr20:58373731-58374925,6352,5325,5863,5154,13441,11243,10748,14765
chr20,58388798,58390769,chr20:58388798-58390769,13398,10811,11295,10943,313336,227771,211741,365207

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_overlap
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 150042
After  removing zero: 823

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4551522,4551988,chr11:4551522-4551988,2304,2303,2349,2157,6129,5659,5936,6630
chr11,4554256,4554817,chr11:4554256-4554817,2685,2503,2501,2702,32516,41800,49258,30079
chr11,4577505,4578002,chr11:4577505-4578002,2570,2674,2782,2650,3988,4184,4413,3599

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58371839,58372138,chr20:58371839-58372138,1678,1547,1693,1644,2307,2047,1947,2346
chr20,58373731,58374925,chr20:58373731-58374925,4676,4626,4963,4437,16550,16891,18187,16487
chr20,58388798,58390769,chr20:58388798-58390769,9863,9392,9561,9420,385829,342196,358295,407824

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_union
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 246852
After  removing zero: 22

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792068,61793464,chr11:61792068-61793464,123964,69072,113487,71526,461111,461000,688001,609101
chr11,61800085,61801113,chr11:61800085-61801113,93429,53063,83490,53637,424590,398992,582993,484099
chr11,61806630,61807154,chr11:61806630-61807154,73252,39188,63205,40131,29775,28918,48404,50335

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61884698,61885718,chr11:61884698-61885718,115136,63883,100642,63530,50683,46624,78644,84355
chr11,61890509,61892327,chr11:61890509-61892327,112803,62214,100836,65270,245008,233120,343157,338396
chr11,61897731,61898477,chr11:61897731-61898477,61588,34333,55715,34880,46946,47779,67870,81991

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_union
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 246852
After  removing zero: 22

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792068,61793464,chr11:61792068-61793464,67941,67680,69549,69457,986584,927937,875552,743792
chr11,61800085,61801113,chr11:61800085-61801113,51206,51993,51166,52086,908445,803122,741919,591148
chr11,61806630,61807154,chr11:61806630-61807154,40147,38398,38734,38970,63706,58208,61599,61465

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61884698,61885718,chr11:61884698-61885718,63103,62595,61677,61693,108440,93848,100082,103008
chr11,61890509,61892327,chr11:61890509-61892327,61824,60960,61796,63382,524214,469242,436702,413226
chr11,61897731,61898477,chr11:61897731-61898477,33754,33641,34144,33871,100444,96173,86371,100121

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_union
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 246852
After  removing zero: 394

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126778902,126779728,chr8:126778902-126779728,10372,11304,10609,11042,5318,5475,38115,23681,54377,40239,43886
chr8,126782925,126783318,chr8:126782925-126783318,3076,3477,3122,3211,1563,1614,2527,1956,3373,2541,2906
chr8,126804776,126805825,chr8:126804776-126805825,16184,18791,17453,17754,8529,8533,64484,43758,74563,56099,64459

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862119,49862823,chrX:49862119-49862823,6971,8227,7538,7373,3724,3755,70321,38699,88737,68017,75013
chrX,49868244,49869175,chrX:49868244-49869175,17904,20627,18745,19115,9208,9085,21439,15496,27682,19255,21758
chrX,49878402,49880117,chrX:49878402-49880117,13413,14976,14462,14353,6892,6888,148773,104195,166435,132240,140171

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_union
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 246852
After  removing zero: 394

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126778902,126779728,chr8:126778902-126779728,6983,6737,6800,6938,6934,7123,59125,42322,58691,69386,62006
chr8,126782925,126783318,chr8:126782925-126783318,2071,2072,2001,2017,2038,2100,3919,3495,3640,4381,4105
chr8,126804776,126805825,chr8:126804776-126805825,10897,11199,11188,11156,11121,11102,100030,78204,80479,96734,91074

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862119,49862823,chrX:49862119-49862823,4693,4903,4832,4633,4855,4885,109085,69163,95778,117285,105986
chrX,49868244,49869175,chrX:49868244-49869175,12055,12293,12016,12011,12006,11821,33257,27694,29878,33202,30742
chrX,49878402,49880117,chrX:49878402-49880117,9031,8925,9270,9019,8986,8962,230783,186218,179641,228028,198048

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_union
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 246852
After  removing zero: 1306

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539569,4540043,chr11:4539569-4540043,3092,2495,2634,2660,2107,1709,1528,2169
chr11,4551336,4552012,chr11:4551336-4552012,4522,3783,4039,3743,6611,4704,4380,7560
chr11,4553969,4555012,chr11:4553969-4555012,5879,4921,5015,5157,28478,29457,30659,29235

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58371827,58372143,chr20:58371827-58372143,2280,1781,2001,1910,1874,1363,1151,2101
chr20,58373695,58375015,chr20:58373695-58375015,7009,5895,6564,5732,14002,11755,11245,15268
chr20,58388793,58390778,chr20:58388793-58390778,13398,10811,11295,10943,313336,227771,211741,365207

====================
Region Folder: region_for_analysis
Region Label:  fcc_astarr_macs_input_union
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 246852
After  removing zero: 1306

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539569,4540043,chr11:4539569-4540043,2276,2167,2229,2289,2594,2567,2585,2422
chr11,4551336,4552012,chr11:4551336-4552012,3329,3286,3419,3222,8140,7067,7411,8442
chr11,4553969,4555012,chr11:4553969-4555012,4327,4275,4245,4439,35066,44255,51879,32646

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58371827,58372143,chr20:58371827-58372143,1678,1547,1693,1644,2307,2047,1947,2346
chr20,58373695,58375015,chr20:58373695-58375015,5159,5121,5556,4934,17241,17660,19028,17049
chr20,58388793,58390778,chr20:58388793-58390778,9863,9392,9561,9420,385829,342196,358295,407824

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF274YGF
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 118721
After  removing zero: 24

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788200,61788380,chr11:61788200-61788380,17592,9987,15292,8792,14436,12389,20782,23865
chr11,61792020,61792200,chr11:61792020-61792200,23456,13266,21945,12530,56331,55843,73755,74092
chr11,61792540,61792720,chr11:61792540-61792720,12741,6910,10211,7154,230794,235208,365333,304715

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61891020,61891320,chr11:61891020-61891320,20324,11244,18069,12473,64338,57118,80553,80555
chr11,61891560,61891820,chr11:61891560-61891820,4453,2248,3859,2310,37353,32188,50327,49237
chr11,61897720,61897920,chr11:61897720-61897920,13343,7402,11384,7385,30764,32107,42797,53907

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF274YGF
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 118721
After  removing zero: 24

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788200,61788380,chr11:61788200-61788380,9641,9785,9371,8537,30887,24937,26447,29142
chr11,61792020,61792200,chr11:61792020-61792200,12855,12998,13448,12167,120524,112405,93860,90476
chr11,61792540,61792720,chr11:61792540-61792720,6983,6770,6257,6947,493802,473445,464924,372097

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61891020,61891320,chr11:61891020-61891320,11139,11017,11073,12112,137656,114971,102512,98368
chr11,61891560,61891820,chr11:61891560-61891820,2440,2202,2364,2243,79919,64790,64046,60124
chr11,61897720,61897920,chr11:61897720-61897920,7312,7252,6976,7171,65822,64627,54463,65827

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF274YGF
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 118721
After  removing zero: 292

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126768703,126768900,chr8:126768703-126768900,3849,4049,3996,3720,1877,1949,1614,1404,2463,1277,1838
chr8,126779150,126779254,chr8:126779150-126779254,4067,4498,4172,4317,2078,2297,3692,3208,5283,3659,4428
chr8,126779297,126779430,chr8:126779297-126779430,2929,3095,2976,3037,1421,1394,32830,18958,46708,35057,37879

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49878500,49878680,chrX:49878500-49878680,730,750,786,798,393,442,1718,1079,2715,2204,2880
chrX,49878900,49879120,chrX:49878900-49879120,3806,4461,4236,4180,2003,2056,70169,51268,79326,65280,68692
chrX,49879320,49879560,chrX:49879320-49879560,566,574,548,650,259,243,17204,11653,18316,14795,15587

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF274YGF
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 118721
After  removing zero: 292

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126768703,126768900,chr8:126768703-126768900,2591,2413,2561,2337,2447,2535,2503,2509,2658,2202,2596
chr8,126779150,126779254,chr8:126779150-126779254,2738,2680,2674,2712,2709,2988,5727,5733,5702,6309,6256
chr8,126779297,126779430,chr8:126779297-126779430,1972,1844,1907,1908,1852,1813,50927,33881,50414,60450,53519

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49878500,49878680,chrX:49878500-49878680,491,447,503,501,512,575,2665,1928,2930,3800,4069
chrX,49878900,49879120,chrX:49878900-49879120,2562,2658,2715,2626,2611,2675,108849,91626,85620,112565,97055
chrX,49879320,49879560,chrX:49879320-49879560,381,342,351,408,337,316,26687,20826,19769,25511,22022

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF274YGF
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 118721
After  removing zero: 615

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539720,4539880,chr11:4539720-4539880,1173,919,1058,918,900,750,716,897
chr11,4551738,4551844,chr11:4551738-4551844,1604,1396,1504,1356,3229,2470,2217,3783
chr11,4607800,4608000,chr11:4607800-4608000,1395,1041,1231,1154,8748,8126,7973,8627

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58388980,58389180,chr20:58388980-58389180,1960,1729,1924,1666,217761,161556,147353,257671
chr20,58389480,58389700,chr20:58389480-58389700,507,307,423,433,24284,16975,15727,28644
chr20,58390420,58390620,chr20:58390420-58390620,1673,1382,1290,1302,26670,16093,16564,24863

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF274YGF
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 118721
After  removing zero: 615

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539720,4539880,chr11:4539720-4539880,863,798,895,790,1108,1126,1211,1001
chr11,4551738,4551844,chr11:4551738-4551844,1180,1212,1273,1167,3976,3710,3751,4224
chr11,4607800,4608000,chr11:4607800-4608000,1026,904,1042,993,10771,12208,13491,9633

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58388980,58389180,chr20:58388980-58389180,1442,1502,1628,1434,268142,242716,249341,287739
chr20,58389480,58389700,chr20:58389480-58389700,373,266,358,372,29902,25502,26612,31986
chr20,58390420,58390620,chr20:58390420-58390620,1231,1200,1092,1120,32840,24177,28028,27764

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF185XRG
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 159277
After  removing zero: 27

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788220,61788380,chr11:61788220-61788380,17275,9772,14936,8682,14288,12415,20562,23816
chr11,61792040,61792200,chr11:61792040-61792200,23303,13264,22047,12597,55687,55145,73444,73384
chr11,61792540,61792720,chr11:61792540-61792720,12741,6910,10211,7154,230794,235208,365333,304715

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61891180,61891360,chr11:61891180-61891360,11173,6625,10182,7274,22891,22441,28383,27614
chr11,61891720,61891880,chr11:61891720-61891880,8233,4130,7096,4573,57640,54503,75141,79471
chr11,61897720,61897900,chr11:61897720-61897900,13200,7379,11391,7357,33012,34159,45368,57005

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF185XRG
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 159277
After  removing zero: 27

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788220,61788380,chr11:61788220-61788380,9467,9575,9153,8430,30570,24989,26167,29082
chr11,61792040,61792200,chr11:61792040-61792200,12771,12996,13511,12232,119146,111000,93465,89611
chr11,61792540,61792720,chr11:61792540-61792720,6983,6770,6257,6947,493802,473445,464924,372097

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61891180,61891360,chr11:61891180-61891360,6123,6491,6239,7063,48977,45171,36120,33720
chr11,61891720,61891880,chr11:61891720-61891880,4512,4046,4348,4440,123325,109707,95624,97044
chr11,61897720,61897900,chr11:61897720-61897900,7234,7230,6980,7144,70631,68757,57735,69610

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF185XRG
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 159277
After  removing zero: 382

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126768725,126768842,chr8:126768725-126768842,4284,4876,4544,4391,2190,2212,5297,3967,6591,4333,5444
chr8,126779040,126779460,chr8:126779040-126779460,6788,7413,6975,7263,3493,3667,36226,21992,51234,38252,41531
chr8,126782844,126782924,chr8:126782844-126782924,1691,1774,1752,1775,781,758,1079,740,1364,1027,1127

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49878520,49878720,chrX:49878520-49878720,813,840,806,846,439,439,2906,1823,4986,3912,4808
chrX,49878940,49879160,chrX:49878940-49879160,3989,4640,4450,4338,2106,2150,71043,51868,80328,65901,69251
chrX,49879280,49879580,chrX:49879280-49879580,2375,2445,2486,2504,1106,1193,48093,31472,49601,38639,41132

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF185XRG
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 159277
After  removing zero: 382

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126768725,126768842,chr8:126768725-126768842,2884,2906,2912,2759,2855,2878,8216,7089,7113,7471,7691
chr8,126779040,126779460,chr8:126779040-126779460,4570,4418,4471,4563,4554,4771,56195,39304,55299,65960,58679
chr8,126782844,126782924,chr8:126782844-126782924,1138,1057,1123,1115,1018,986,1673,1322,1472,1770,1592

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49878520,49878720,chrX:49878520-49878720,547,500,516,531,572,571,4507,3258,5381,6745,6793
chrX,49878940,49879160,chrX:49878940-49879160,2685,2765,2852,2725,2746,2797,110205,92699,86701,113636,97845
chrX,49879280,49879580,chrX:49879280-49879580,1599,1457,1593,1573,1442,1552,74604,56247,53536,66627,58115

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF185XRG
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 159277
After  removing zero: 839

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539720,4539880,chr11:4539720-4539880,1173,919,1058,918,900,750,716,897
chr11,4543758,4543816,chr11:4543758-4543816,1704,1547,1568,1408,46133,33441,33057,60617
chr11,4551700,4551860,chr11:4551700-4551860,1604,1396,1504,1356,3229,2470,2217,3783

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58389820,58390160,chr20:58389820-58390160,3425,2591,2585,2619,1830,1510,1297,1777
chr20,58390420,58390620,chr20:58390420-58390620,1673,1382,1290,1302,26670,16093,16564,24863
chr20,58391146,58391197,chr20:58391146-58391197,2085,1654,2130,2005,2517,1870,2041,2726

====================
Region Folder: region_for_analysis
Region Label:  dnase_ENCFF185XRG
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 159277
After  removing zero: 839

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539720,4539880,chr11:4539720-4539880,863,798,895,790,1108,1126,1211,1001
chr11,4543758,4543816,chr11:4543758-4543816,1254,1344,1327,1212,56806,50240,55937,67690
chr11,4551700,4551860,chr11:4551700-4551860,1180,1212,1273,1167,3976,3710,3751,4224

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58389820,58390160,chr20:58389820-58390160,2521,2251,2188,2254,2253,2268,2194,1984
chr20,58390420,58390620,chr20:58390420-58390620,1231,1200,1092,1120,32840,24177,28028,27764
chr20,58391146,58391197,chr20:58391146-58391197,1534,1437,1803,1726,3099,2809,3453,3044

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF558BLC
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 107082
After  removing zero: 16

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792028,61793545,chr11:61792028-61793545,137161,76658,125396,79066,470547,472055,701705,624343
chr11,61797271,61797472,chr11:61797271-61797472,17329,9823,15353,10132,38567,43046,54455,54130
chr11,61800527,61801098,chr11:61800527-61801098,43490,24950,39190,25227,385590,361578,528704,427362

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885706,chr11:61885073-61885706,70024,38563,62129,38934,36527,33344,55115,59167
chr11,61890597,61892182,chr11:61890597-61892182,85855,47884,76013,50066,235972,222859,329041,324180
chr11,61897665,61897953,chr11:61897665-61897953,18922,10674,16827,10746,38736,39286,53136,65000

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF558BLC
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 107082
After  removing zero: 16

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792028,61793545,chr11:61792028-61793545,75174,75113,76848,76779,1006774,950189,892992,762405
chr11,61797271,61797472,chr11:61797271-61797472,9497,9625,9409,9839,82517,86646,69299,66099
chr11,61800527,61801098,chr11:61800527-61801098,23835,24447,24017,24497,825001,727812,672830,521865

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885706,chr11:61885073-61885706,38378,37785,38075,37808,78152,67117,70139,72250
chr11,61890597,61892182,chr11:61890597-61892182,47054,46919,46584,48618,504881,448588,418738,395866
chr11,61897665,61897953,chr11:61897665-61897953,10370,10458,10312,10435,82878,79077,67621,79373

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF558BLC
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 107082
After  removing zero: 231

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126809972,126810178,chr8:126809972-126810178,5088,5933,5505,5376,2745,2686,7855,6473,9656,6961,7861
chr8,126817161,126817342,chr8:126817161-126817342,3183,3673,3303,3416,1612,1621,2809,2320,3448,2412,2751
chr8,126820500,126821261,chr8:126820500-126821261,16085,18409,16652,17274,8439,8414,17833,13997,23655,15699,17451

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862146,49862424,chrX:49862146-49862424,5825,6724,6210,6048,3065,3086,69615,38142,87764,67392,74289
chrX,49868850,49869059,chrX:49868850-49869059,3365,3891,3417,3731,1755,1641,12553,8031,14426,10606,12150
chrX,49878523,49880019,chrX:49878523-49880019,11568,13014,12511,12482,5974,5994,147569,103305,164959,131197,139009

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF558BLC
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 107082
After  removing zero: 231

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126809972,126810178,chr8:126809972-126810178,3425,3536,3528,3378,3579,3494,12185,11568,10422,12003,11106
chr8,126817161,126817342,chr8:126817161-126817342,2143,2189,2117,2146,2101,2109,4357,4146,3721,4159,3886
chr8,126820500,126821261,chr8:126820500-126821261,10830,10971,10674,10854,11004,10948,27663,25015,25531,27070,24656

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862146,49862424,chrX:49862146-49862424,3922,4007,3980,3800,3996,4015,107989,68167,94727,116207,104963
chrX,49868850,49869059,chrX:49868850-49869059,2265,2319,2190,2344,2288,2135,19472,14353,15570,18288,17166
chrX,49878523,49880019,chrX:49878523-49880019,7789,7756,8020,7843,7789,7799,228915,184628,178048,226230,196406

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF558BLC
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 107082
After  removing zero: 593

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539686,4539920,chr11:4539686-4539920,1848,1471,1609,1618,1320,956,961,1262
chr11,4607724,4608649,chr11:4607724-4608649,7957,6823,6814,6785,57522,44355,42817,64258
chr11,4619478,4619925,chr11:4619478-4619925,3464,2977,2873,3011,33394,22912,21689,31327

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375061,chr20:58373878-58375061,5481,4661,5162,4499,13163,10977,10528,14493
chr20,58388901,58389923,chr20:58388901-58389923,4571,3660,4203,3816,282296,208267,192286,335672
chr20,58390403,58390675,chr20:58390403-58390675,1673,1382,1290,1302,26670,16093,16564,24863

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF558BLC
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 107082
After  removing zero: 593

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539686,4539920,chr11:4539686-4539920,1360,1278,1362,1392,1625,1436,1626,1409
chr11,4607724,4608649,chr11:4607724-4608649,5857,5927,5768,5841,70830,66637,72452,71756
chr11,4619478,4619925,chr11:4619478-4619925,2550,2586,2432,2592,41120,34422,36700,34982

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375061,chr20:58373878-58375061,4034,4049,4369,3873,16208,16491,17814,16184
chr20,58388901,58389923,chr20:58388901-58389923,3365,3179,3558,3285,347608,312893,325374,374842
chr20,58390403,58390675,chr20:58390403-58390675,1231,1200,1092,1120,32840,24177,28028,27764

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF925CYR
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 51861
After  removing zero: 12

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792028,61793545,chr11:61792028-61793545,137161,76658,125396,79066,470547,472055,701705,624343
chr11,61800527,61801098,chr11:61800527-61801098,43490,24950,39190,25227,385590,361578,528704,427362
chr11,61814956,61816302,chr11:61814956-61816302,107719,60164,97173,59881,1257277,1271894,1736720,1546743

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885706,chr11:61885073-61885706,70024,38563,62129,38934,36527,33344,55115,59167
chr11,61890597,61892182,chr11:61890597-61892182,85855,47884,76013,50066,235972,222859,329041,324180
chr11,61897665,61897953,chr11:61897665-61897953,18922,10674,16827,10746,38736,39286,53136,65000

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF925CYR
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 51861
After  removing zero: 12

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61792028,61793545,chr11:61792028-61793545,75174,75113,76848,76779,1006774,950189,892992,762405
chr11,61800527,61801098,chr11:61800527-61801098,23835,24447,24017,24497,825001,727812,672830,521865
chr11,61814956,61816302,chr11:61814956-61816302,59037,58951,59551,58149,2690047,2560169,2210156,1888777

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885706,chr11:61885073-61885706,38378,37785,38075,37808,78152,67117,70139,72250
chr11,61890597,61892182,chr11:61890597-61892182,47054,46919,46584,48618,504881,448588,418738,395866
chr11,61897665,61897953,chr11:61897665-61897953,10370,10458,10312,10435,82878,79077,67621,79373

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF925CYR
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 51861
After  removing zero: 122

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126820500,126821261,chr8:126820500-126821261,16085,18409,16652,17274,8439,8414,17833,13997,23655,15699,17451
chr8,126876475,126877111,chr8:126876475-126877111,25715,29443,27362,27623,13434,13362,60499,44917,70136,50886,56495
chr8,127496506,127496685,chr8:127496506-127496685,2912,3183,3012,3132,1327,1496,2296,2048,2951,2139,2206

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49829072,49829345,chrX:49829072-49829345,3820,4432,4100,3905,1993,2105,56705,34360,58879,47058,51248
chrX,49829431,49829626,chrX:49829431-49829626,1514,1490,1505,1548,726,761,612,497,937,454,777
chrX,49878523,49880019,chrX:49878523-49880019,11568,13014,12511,12482,5974,5994,147569,103305,164959,131197,139009

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF925CYR
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 51861
After  removing zero: 122

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126820500,126821261,chr8:126820500-126821261,10830,10971,10674,10854,11004,10948,27663,25015,25531,27070,24656
chr8,126876475,126877111,chr8:126876475-126877111,17314,17548,17540,17357,17517,17386,93848,80276,75701,87745,79822
chr8,127496506,127496685,chr8:127496506-127496685,1960,1897,1930,1968,1730,1946,3561,3660,3185,3688,3116

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49829072,49829345,chrX:49829072-49829345,2572,2641,2628,2453,2598,2738,87963,61408,63550,81144,72408
chrX,49829431,49829626,chrX:49829431-49829626,1019,888,964,972,946,990,949,888,1011,782,1097
chrX,49878523,49880019,chrX:49878523-49880019,7789,7756,8020,7843,7789,7799,228915,184628,178048,226230,196406

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF925CYR
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 51861
After  removing zero: 290

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539686,4539920,chr11:4539686-4539920,1848,1471,1609,1618,1320,956,961,1262
chr11,4607724,4608649,chr11:4607724-4608649,7957,6823,6814,6785,57522,44355,42817,64258
chr11,4626265,4626702,chr11:4626265-4626702,3852,3351,3500,3384,12891,10126,8673,14358

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375061,chr20:58373878-58375061,5481,4661,5162,4499,13163,10977,10528,14493
chr20,58388901,58389923,chr20:58388901-58389923,4571,3660,4203,3816,282296,208267,192286,335672
chr20,58390403,58390675,chr20:58390403-58390675,1673,1382,1290,1302,26670,16093,16564,24863

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF925CYR
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 51861
After  removing zero: 290

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539686,4539920,chr11:4539686-4539920,1360,1278,1362,1392,1625,1436,1626,1409
chr11,4607724,4608649,chr11:4607724-4608649,5857,5927,5768,5841,70830,66637,72452,71756
chr11,4626265,4626702,chr11:4626265-4626702,2835,2911,2962,2913,15873,15212,14675,16033

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375061,chr20:58373878-58375061,4034,4049,4369,3873,16208,16491,17814,16184
chr20,58388901,58389923,chr20:58388901-58389923,3365,3179,3558,3285,347608,312893,325374,374842
chr20,58390403,58390675,chr20:58390403-58390675,1231,1200,1092,1120,32840,24177,28028,27764

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF333TAT
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 161693
After  removing zero: 20

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788184,61788431,chr11:61788184-61788431,21142,12107,19140,11081,15259,13477,22255,25813
chr11,61792001,61793509,chr11:61792001-61793509,137188,76356,125185,78629,471984,473107,702490,627019
chr11,61797264,61797485,chr11:61797264-61797485,18814,11066,16816,11195,39085,43407,55386,54939

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885709,chr11:61885073-61885709,70303,38710,62395,39129,36690,33511,55316,59418
chr11,61890548,61892196,chr11:61890548-61892196,91911,50946,81253,53764,238107,225845,332877,328144
chr11,61897665,61898277,chr11:61897665-61898277,65148,36402,59125,36897,57156,57048,82474,97310

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF333TAT
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 161693
After  removing zero: 20

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788184,61788431,chr11:61788184-61788431,11587,11863,11729,10760,32647,27127,28321,31521
chr11,61792001,61793509,chr11:61792001-61793509,75189,74817,76719,76355,1009848,952307,893991,765673
chr11,61797264,61797485,chr11:61797264-61797485,10311,10843,10305,10871,83625,87373,70484,67087

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885709,chr11:61885073-61885709,38531,37930,38238,37997,78501,67453,70395,72557
chr11,61890548,61892196,chr11:61890548-61892196,50374,49919,49795,52209,509449,454598,423620,400707
chr11,61897665,61898277,chr11:61897665-61898277,35705,35668,36234,35830,122289,114830,104956,118828

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF333TAT
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 161693
After  removing zero: 337

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126768673,126768877,chr8:126768673-126768877,4284,4876,4544,4391,2190,2212,5297,3967,6591,4333,5444
chr8,126809933,126810214,chr8:126809933-126810214,6822,7756,7113,7186,3701,3455,8469,7041,10665,7489,8731
chr8,126817119,126817375,chr8:126817119-126817375,4692,5276,4884,5036,2301,2336,4966,3945,6016,4171,4843

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862128,49862464,chrX:49862128-49862464,6170,7216,6562,6413,3280,3297,69758,38273,87936,67530,74437
chrX,49868259,49869078,chrX:49868259-49869078,16188,18605,17060,17396,8404,8230,20856,14740,26676,18653,20980
chrX,49878456,49880026,chrX:49878456-49880026,11781,13241,12772,12724,6076,6128,147677,103416,165056,131303,139141

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF333TAT
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 161693
After  removing zero: 337

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126768673,126768877,chr8:126768673-126768877,2884,2906,2912,2759,2855,2878,8216,7089,7113,7471,7691
chr8,126809933,126810214,chr8:126809933-126810214,4593,4622,4559,4515,4825,4495,13137,12583,11511,12913,12336
chr8,126817119,126817375,chr8:126817119-126817375,3159,3144,3130,3164,3000,3039,7703,7050,6493,7192,6842

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862128,49862464,chrX:49862128-49862464,4154,4300,4206,4029,4276,4289,108211,68401,94913,116445,105172
chrX,49868259,49869078,chrX:49868259-49869078,10899,11088,10936,10931,10958,10708,32352,26343,28792,32164,29642
chrX,49878456,49880026,chrX:49878456-49880026,7932,7891,8187,7995,7922,7973,229083,184826,178152,226413,196593

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF333TAT
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 161693
After  removing zero: 834

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539689,4539929,chr11:4539689-4539929,1848,1471,1609,1618,1320,956,961,1262
chr11,4551483,4551895,chr11:4551483-4551895,3344,2662,2886,2729,5196,3768,3521,5876
chr11,4577086,4577738,chr11:4577086-4577738,5802,5073,5390,4808,5164,4713,4302,5651

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375214,chr20:58373878-58375214,5481,4661,5162,4499,13163,10977,10528,14493
chr20,58388889,58389983,chr20:58388889-58389983,5107,4142,4650,4301,282812,208676,192548,335997
chr20,58390200,58390736,chr20:58390200-58390736,5486,4526,4523,4479,29346,18270,18427,27972

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF333TAT
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 161693
After  removing zero: 834

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539689,4539929,chr11:4539689-4539929,1360,1278,1362,1392,1625,1436,1626,1409
chr11,4551483,4551895,chr11:4551483-4551895,2461,2312,2443,2349,6398,5660,5958,6561
chr11,4577086,4577738,chr11:4577086-4577738,4271,4407,4562,4139,6358,7080,7279,6310

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375214,chr20:58373878-58375214,4034,4049,4369,3873,16208,16491,17814,16184
chr20,58388889,58389983,chr20:58388889-58389983,3759,3598,3936,3702,348243,313508,325817,375205
chr20,58390200,58390736,chr20:58390200-58390736,4038,3932,3828,3855,36135,27448,31181,31236

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF948AFM
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 90015
After  removing zero: 15

Save count matrix and data list.
matrix.count.raw.OL13.tsv
data.count_column.raw.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788184,61788431,chr11:61788184-61788431,21142,12107,19140,11081,15259,13477,22255,25813
chr11,61792001,61793509,chr11:61792001-61793509,137188,76356,125185,78629,471984,473107,702490,627019
chr11,61797264,61797485,chr11:61797264-61797485,18814,11066,16816,11195,39085,43407,55386,54939

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885709,chr11:61885073-61885709,70303,38710,62395,39129,36690,33511,55316,59418
chr11,61890548,61892196,chr11:61890548-61892196,91911,50946,81253,53764,238107,225845,332877,328144
chr11,61897665,61898277,chr11:61897665-61898277,65148,36402,59125,36897,57156,57048,82474,97310

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF948AFM
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL13_20220512.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL13_20220512.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 90015
After  removing zero: 15

Save count matrix and data list.
matrix.count.norm.OL13.tsv
data.count_column.norm.OL13.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61788184,61788431,chr11:61788184-61788431,11587,11863,11729,10760,32647,27127,28321,31521
chr11,61792001,61793509,chr11:61792001-61793509,75189,74817,76719,76355,1009848,952307,893991,765673
chr11,61797264,61797485,chr11:61797264-61797485,10311,10843,10305,10871,83625,87373,70484,67087

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,61885073,61885709,chr11:61885073-61885709,38531,37930,38238,37997,78501,67453,70395,72557
chr11,61890548,61892196,chr11:61890548-61892196,50374,49919,49795,52209,509449,454598,423620,400707
chr11,61897665,61898277,chr11:61897665-61898277,35705,35668,36234,35830,122289,114830,104956,118828

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF948AFM
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.raw.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.raw.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 90015
After  removing zero: 209

Save count matrix and data list.
matrix.count.raw.OL43.tsv
data.count_column.raw.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126809933,126810214,chr8:126809933-126810214,6822,7756,7113,7186,3701,3455,8469,7041,10665,7489,8731
chr8,126817119,126817375,chr8:126817119-126817375,4692,5276,4884,5036,2301,2336,4966,3945,6016,4171,4843
chr8,126820507,126821268,chr8:126820507-126821268,14855,16936,15387,15912,7822,7750,16380,12532,21712,14399,16094

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862128,49862464,chrX:49862128-49862464,6170,7216,6562,6413,3280,3297,69758,38273,87936,67530,74437
chrX,49868259,49869078,chrX:49868259-49869078,16188,18605,17060,17396,8404,8230,20856,14740,26676,18653,20980
chrX,49878456,49880026,chrX:49878456-49880026,11781,13241,12772,12724,6076,6128,147677,103416,165056,131303,139141

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF948AFM
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
 [1] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep1.stranded_pos.bed.gz"
 [2] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep2.stranded_pos.bed.gz"
 [3] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep3.stranded_pos.bed.gz"
 [4] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep4.stranded_pos.bed.gz"
 [5] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep5.stranded_pos.bed.gz"
 [6] "TMPRA_K562_OL43_20221003.hg38.norm.Input.rep6.stranded_pos.bed.gz"
 [7] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep1.stranded_pos.bed.gz"
 [8] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep2.stranded_pos.bed.gz"
 [9] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[10] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep4.stranded_pos.bed.gz"
[11] "TMPRA_K562_OL43_20221003.hg38.norm.Output.rep5.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 90015
After  removing zero: 209

Save count matrix and data list.
matrix.count.norm.OL43.tsv
data.count_column.norm.OL43.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chr8,126809933,126810214,chr8:126809933-126810214,4593,4622,4559,4515,4825,4495,13137,12583,11511,12913,12336
chr8,126817119,126817375,chr8:126817119-126817375,3159,3144,3130,3164,3000,3039,7703,7050,6493,7192,6842
chr8,126820507,126821268,chr8:126820507-126821268,10002,10093,9863,9998,10199,10084,25409,22397,23434,24829,22739

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Input.rep5,Input.rep6,Output.rep1,Output.rep2,Output.rep3,Output.rep4,Output.rep5
chrX,49862128,49862464,chrX:49862128-49862464,4154,4300,4206,4029,4276,4289,108211,68401,94913,116445,105172
chrX,49868259,49869078,chrX:49868259-49869078,10899,11088,10936,10931,10958,10708,32352,26343,28792,32164,29642
chrX,49878456,49880026,chrX:49878456-49880026,7932,7891,8187,7995,7922,7973,229083,184826,178152,226413,196593

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF948AFM
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.raw.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.raw.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 90015
After  removing zero: 477

Save count matrix and data list.
matrix.count.raw.OL45.tsv
data.count_column.raw.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539689,4539929,chr11:4539689-4539929,1848,1471,1609,1618,1320,956,961,1262
chr11,4551483,4551895,chr11:4551483-4551895,3344,2662,2886,2729,5196,3768,3521,5876
chr11,4607721,4608667,chr11:4607721-4608667,7957,6823,6814,6785,57522,44355,42817,64258

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375214,chr20:58373878-58375214,5481,4661,5162,4499,13163,10977,10528,14493
chr20,58388889,58389983,chr20:58388889-58389983,5107,4142,4650,4301,282812,208676,192548,335997
chr20,58390200,58390736,chr20:58390200-58390736,5486,4526,4523,4479,29346,18270,18427,27972

====================
Region Folder: region_for_analysis
Region Label:  atac_ENCFF948AFM
Assay  Folder: MPRA_Tiling_K562_Tewhey_Hannah
Import Counts:
[1] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep1.stranded_pos.bed.gz"
[2] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep2.stranded_pos.bed.gz"
[3] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep3.stranded_pos.bed.gz"
[4] "TMPRA_K562_OL45_20220927.hg38.norm.Input.rep4.stranded_pos.bed.gz"
[5] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep1.stranded_pos.bed.gz"
[6] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep2.stranded_pos.bed.gz"
[7] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep3.stranded_pos.bed.gz"
[8] "TMPRA_K562_OL45_20220927.hg38.norm.Output.rep4.stranded_pos.bed.gz"

Removing zero:
Before removing zero: 90015
After  removing zero: 477

Save count matrix and data list.
matrix.count.norm.OL45.tsv
data.count_column.norm.OL45.rds

First few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr11,4539689,4539929,chr11:4539689-4539929,1360,1278,1362,1392,1625,1436,1626,1409
chr11,4551483,4551895,chr11:4551483-4551895,2461,2312,2443,2349,6398,5660,5958,6561
chr11,4607721,4608667,chr11:4607721-4608667,5857,5927,5768,5841,70830,66637,72452,71756

Last few rows of the matrix:

Chrom,ChromStart,ChromEnd,Region,Input.rep1,Input.rep2,Input.rep3,Input.rep4,Output.rep1,Output.rep2,Output.rep3,Output.rep4
chr20,58373878,58375214,chr20:58373878-58375214,4034,4049,4369,3873,16208,16491,17814,16184
chr20,58388889,58389983,chr20:58388889-58389983,3759,3598,3936,3702,348243,313508,325817,375205
chr20,58390200,58390736,chr20:58390200-58390736,4038,3932,3828,3855,36135,27448,31181,31236