---
title: ...
subtitle: ...
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project_sing.R")))
show_env()

You are working on        Singularity
BASE DIRECTORY (FD_BASE): /mount
REPO DIRECTORY (FD_REPO): /mount/repo
WORK DIRECTORY (FD_WORK): /mount/work
DATA DIRECTORY (FD_DATA): /mount/data

You are working with      ENCODE FCC
PATH OF PROJECT (FD_PRJ): /mount/repo/Proj_ENCODE_FCC
PROJECT RESULTS (FD_RES): /mount/repo/Proj_ENCODE_FCC/results
PROJECT SCRIPTS (FD_EXE): /mount/repo/Proj_ENCODE_FCC/scripts
PROJECT DATA    (FD_DAT): /mount/repo/Proj_ENCODE_FCC/data
PROJECT NOTE    (FD_NBK): /mount/repo/Proj_ENCODE_FCC/notebooks
PROJECT DOCS    (FD_DOC): /mount/repo/Proj_ENCODE_FCC/docs
PROJECT LOG     (FD_LOG): /mount/repo/Proj_ENCODE_FCC/log
PROJECT APP     (FD_APP): /mount/repo/Proj_ENCODE_FCC/app
PROJECT REF     (FD_REF): /mount/repo/Proj_ENCODE_FCC/references

In [ ]:
VEC_TXT_ASSAY = c(
    "STARR_ATAC_K562_Reddy_KS91",
    "STARR_ATAC_K562_Reddy_KS274",
    "STARR_ATAC_K562_Reddy_KSMerge",
    "STARR_WHG_K562_Reddy_A001",
    "MPRA_Lenti_K562_Nadav_Vikram", 
    "MPRA_Tiling_K562_Tewhey_Hannah", 
    "CRISPRi_FlowFISH_K562_Riley_JinWoo",
    "CRISPRi_Growth_K562_Gersbach_JinWoo" 
)

VEC_TXT_LABEL = c(
    "ASTARR_KS91",
    "ASTARR_KS274",
    "ASTARR_KSMerge",
    "WSTARR",
    "LMPRA", 
    "TMPRA", 
    "CRISPRi_HCRFF",
    "CRISPRi_Growth" 
)

fun_get_assay = function(txt){
    res = fun_str_map_detect(txt, VEC_TXT_ASSAY, VEC_TXT_LABEL)
    return(res)
}

In [ ]:
txt_fdiry = file.path(FD_RES, "region_coverage_fcc", "fcc_astarr_macs_input_overlap")
txt_fname = "result.score.tsv"
txt_fglob = file.path(txt_fdiry, "*", "*", "summary", txt_fname)

vec = Sys.glob(txt_fglob)
lst = lapply(vec, function(txt_fpath){
    dat = read_tsv(txt_fpath, show_col_types = FALSE)
    return(dat)
})

In [3]:
txt_fdiry = file.path(FD_RES, "region_coverage_fcc", "fcc_astarr_macs_input_overlap")
txt_fname = "result.score.tsv"
txt_fglob = file.path(txt_fdiry, "*", "*", "summary", txt_fname)

vec = Sys.glob(txt_fglob)
lst = lapply(vec, function(txt_fpath){
    dat = read_tsv(txt_fpath, show_col_types = FALSE)
    return(dat)
})

In [5]:
fun_display_table(head(lst[[1]]))

Chrom,ChromStart,ChromEnd,Region,Mean,Median,AbsMax,Max,Min,Count,Mean_Neg,Mean_Pos,Target_CAPRIN1,Target_CAT,Target_CD164,Target_ERP29,Target_FADS1,Target_FADS2,Target_FADS3,Target_FEN1,Target_GATA1,Target_HBE1,Target_HBG1,Target_HBG2,Target_HBS1L,Target_HDAC6,Target_LMO2,Target_MEF2C,Target_MYB,Target_MYC,Target_NMU,Target_PVT1
chr10,100729094,100729750,chr10:100729094-100729750,-0.0770856,-0.155771,-1.82683,1.63462,-1.82683,84,-0.5187814,0.4839875,-0.0293407,-0.0232081,-0.3693438,0.4447452,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,0.0534315,-0.4537152,NA,NA,-0.1621681,NA
chr10,100743501,100744571,chr10:100743501-100744571,-0.0635050,-0.101530,-1.97401,1.83498,-1.97401,147,-0.4956430,0.5126791,-0.1292172,-0.4828771,0.2229348,0.0833267,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,-0.1640059,0.1591823,NA,NA,-0.1338784,NA
chr10,100745413,100745741,chr10:100745413-100745741,0.0800352,0.111189,2.60601,2.60601,-2.44093,42,-0.8476507,0.7108616,0.4235642,0.6766427,-0.5305453,-0.1555092,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,-0.1335742,-0.0048538,NA,NA,0.2845222,NA
chr10,100827671,100829454,chr10:100827671-100829454,-0.0451764,-0.086142,2.97608,2.97608,-1.97879,210,-0.5542560,0.5593556,0.0868731,-0.1350247,-0.0155093,0.1029290,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,-0.1139037,-0.1202471,NA,NA,-0.1213522,NA
chr11,4092109,4092511,chr11:4092109-4092511,-0.1294364,-0.154327,-2.05570,1.47841,-2.05570,320,-0.5218713,0.4669411,NA,NA,NA,NA,NA,NA,NA,NA,NA,-0.1137124,-0.1517430,-0.2425928,-0.0471902,NA,NA,NA,-0.0919436,NA,NA,NA
chr11,4094223,4095304,chr11:4094223-4095304,-0.0484957,-0.045032,-3.02950,2.38441,-3.02950,1030,-0.5075883,0.4673919,NA,NA,NA,NA,NA,NA,NA,NA,NA,-0.2516657,-0.0611086,-0.0201760,-0.0041318,NA,NA,NA,0.0946038,NA,NA,NA