---
title: Prepare Hi-C data 23 (deep intact Hi-C)
subtitle: Prepare data (Loop)
format:
    html:
        code-fold:  true
        code-tools: true
---

**Set environment**

In [1]:
suppressMessages(suppressWarnings(source("../run_config_project_sing.R")))
show_env()

You are working on        Singularity
BASE DIRECTORY (FD_BASE): /mount
REPO DIRECTORY (FD_REPO): /mount/repo
WORK DIRECTORY (FD_WORK): /mount/work
DATA DIRECTORY (FD_DATA): /mount/data

You are working with      ENCODE FCC
PATH OF PROJECT (FD_PRJ): /mount/repo/Proj_ENCODE_FCC
PROJECT RESULTS (FD_RES): /mount/repo/Proj_ENCODE_FCC/results
PROJECT SCRIPTS (FD_EXE): /mount/repo/Proj_ENCODE_FCC/scripts
PROJECT DATA    (FD_DAT): /mount/repo/Proj_ENCODE_FCC/data
PROJECT NOTE    (FD_NBK): /mount/repo/Proj_ENCODE_FCC/notebooks
PROJECT DOCS    (FD_DOC): /mount/repo/Proj_ENCODE_FCC/docs
PROJECT LOG     (FD_LOG): /mount/repo/Proj_ENCODE_FCC/log
PROJECT APP     (FD_APP): /mount/repo/Proj_ENCODE_FCC/app
PROJECT REF     (FD_REF): /mount/repo/Proj_ENCODE_FCC/references

**Set global variables**

In [2]:
TXT_FOLDER_REGION = "hic_intact_K562_deep"
TXT_ASSAY = "hic_intact"
TXT_INDEX = "deep"

## Import data

In [3]:
txt_folder = TXT_FOLDER_REGION
txt_fdiry  = file.path(FD_DAT, "external", txt_folder)

vec = dir(txt_fdiry)
for (txt in vec){cat(txt, "\n")}

inter.hic
localizedList_primary_10.bedpe

In [4]:
### set file path
txt_folder = TXT_FOLDER_REGION
txt_fdiry  = file.path(FD_DAT, "external", txt_folder)
txt_fname = "localizedList_primary_10.bedpe"
txt_fpath = file.path(txt_fdiry, txt_fname)

### read table
dat = read_tsv(txt_fpath, show_col_types = FALSE)

### arrange columns
dat = dat %>% dplyr::filter(!row_number() == 1)
colnames(dat)[1] = "chr"

### assign and show
dat_region_import = dat
print(dim(dat))
fun_display_table(head(dat))

Warning message:
“One or more parsing issues, call `problems()` on your data frame for details, e.g.:
  dat <- vroom(...)
  problems(dat)”

[1] 128714     46

chr,x1,x2,chr2,y1,y2,name,score,strand1,strand2,color,observed,expectedBL,expectedDonut,expectedH,expectedV,fdrBL,fdrDonut,fdrH,fdrV,numCollapsed,centroid1,centroid2,radius,coarse_start_1,coarse_end_1,coarse_start_2,coarse_end_2,highRes_start_1,highRes_end_1,highRes_start_2,highRes_end_2,upstream_start_1,upstream_end_1,downstream_start_2,downstream_end_2,localX,localY,localObserved,localPval,localPeakZ,local_xwidth1,local_xwidth2,local_ywidth1,local_ywidth2,localPeakID
chr10,72223000,72224000,chr10,72328000,72329000,.,.,.,.,"0,255,255",60,12.950622,14.944992,18.595566,18.778150,0e+00,0.0e+00,0.0e+00,0e+00,8,72220750,72327500,3750,72215000,72225000,72328000,72345000,72222989,72223052,72328356,72328539,72223010,72223029,72328356,72328539,72223010,72328480,28,0.0067035,3.735599,910,1320,180,480,0
chr10,64041000,64042000,chr10,67697000,67698000,.,.,.,.,"0,255,255",13,2.119335,2.572927,2.681352,2.459610,4e-07,3.2e-06,5.0e-06,2e-06,1,64041500,67697500,0,64040000,64045000,67695000,67700000,64041355,64041394,67697812,67697897,64041355,64041394,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
chr10,78302000,78304000,chr10,79194000,79196000,.,.,.,.,"0,255,255",26,6.170224,7.191248,7.988020,7.100617,0e+00,1.0e-07,4.0e-07,1e-07,2,78303000,79196000,1000,78300000,78305000,79194000,79200000,NA,NA,79195411,79195658,NA,NA,79195411,79195658,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
chr10,13372000,13373000,chr10,13404000,13405000,.,.,.,.,"0,255,255",46,18.551110,17.287748,20.853645,18.435337,1e-07,0.0e+00,1.4e-06,1e-07,1,13372500,13404500,0,13370000,13380000,13403500,13405500,13372053,13372086,13404380,13404590,13372049,13372086,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA
chr10,132388000,132389000,chr10,132637000,132638000,.,.,.,.,"0,255,255",17,1.521528,1.844521,2.555209,2.371079,0e+00,0.0e+00,0.0e+00,0e+00,1,132388500,132637500,0,132380000,132390000,132637000,132640000,132388085,132388164,132637827,132638023,132388085,132388164,132637827,132638023,132388100,132637710,6,0.0292447,2.577377,260,170,170,190,0
chr10,114550000,114552000,chr10,114876000,114878000,.,.,.,.,"0,255,255",26,6.588489,6.097703,7.046953,7.528761,0e+00,0.0e+00,1.0e-07,1e-07,4,114550000,114878000,1414,114545000,114552000,114870000,114880000,114548865,114548904,114877201,114877299,114550810,114551020,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA,NA

## Arrange loops

In [5]:
### init
dat = dat_region_import
vec_txt_cname1 = c(
    "chr",  "x1", "x2", 
    "chr2", "y1", "y2", 
    "observed", "centroid1", "centroid2", "radius"
)
vec_txt_cname2 = c(
    "Chrom_A", "ChromStart_A", "ChromEnd_A",
    "Chrom_B", "ChromStart_B", "ChromEnd_B",
    "Observed", "Centroid_A", "Centroid_B", "Radius"
)
vec_txt_cname3 = c(
    "Chrom_A", "ChromStart_A", "ChromEnd_A", "Region_A", "Length_A",
    "Chrom_B", "ChromStart_B", "ChromEnd_B", "Region_B", "Length_B",
    "Name", 
    "Observed", "Centroid_A", "Centroid_B", 
    "Radius", "Distance", "Size"
)

### get columns
dat = dat %>% dplyr::select(!!!vec_txt_cname1)
colnames(dat) = vec_txt_cname2

### arrange columns
dat = dat %>% 
    dplyr::mutate(
        Length_A = ChromEnd_A - ChromStart_A,
        Length_B = ChromEnd_B - ChromStart_B,
        Size     = (Length_A + Length_B) / 2,
        Region_A = paste0(Chrom_A, ":", ChromStart_A, "-", ChromEnd_A),
        Region_B = paste0(Chrom_B, ":", ChromStart_B, "-", ChromEnd_B),
        Name     = paste0(Region_A, "|", Region_B),
        Distance = Centroid_B - Centroid_A
    ) %>%
    dplyr::select(!!!vec_txt_cname3) %>%
    dplyr::distinct()

### assign and show
dat_region_arrange = dat
print(dim(dat))
fun_display_table(head(dat))

[1] 128714     17

Chrom_A,ChromStart_A,ChromEnd_A,Region_A,Length_A,Chrom_B,ChromStart_B,ChromEnd_B,Region_B,Length_B,Name,Observed,Centroid_A,Centroid_B,Radius,Distance,Size
chr10,72223000,72224000,chr10:72223000-72224000,1000,chr10,72328000,72329000,chr10:72328000-72329000,1000,chr10:72223000-72224000|chr10:72328000-72329000,60,72220750,72327500,3750,106750,1000
chr10,64041000,64042000,chr10:64041000-64042000,1000,chr10,67697000,67698000,chr10:67697000-67698000,1000,chr10:64041000-64042000|chr10:67697000-67698000,13,64041500,67697500,0,3656000,1000
chr10,78302000,78304000,chr10:78302000-78304000,2000,chr10,79194000,79196000,chr10:79194000-79196000,2000,chr10:78302000-78304000|chr10:79194000-79196000,26,78303000,79196000,1000,893000,2000
chr10,13372000,13373000,chr10:13372000-13373000,1000,chr10,13404000,13405000,chr10:13404000-13405000,1000,chr10:13372000-13373000|chr10:13404000-13405000,46,13372500,13404500,0,32000,1000
chr10,132388000,132389000,chr10:132388000-132389000,1000,chr10,132637000,132638000,chr10:132637000-132638000,1000,chr10:132388000-132389000|chr10:132637000-132638000,17,132388500,132637500,0,249000,1000
chr10,114550000,114552000,chr10:114550000-114552000,2000,chr10,114876000,114878000,chr10:114876000-114878000,2000,chr10:114550000-114552000|chr10:114876000-114878000,26,114550000,114878000,1414,328000,2000

**Check**

In [6]:
dat = dat_region_arrange
all(dat$Length_A == dat$Length_B)

[1] TRUE

## Prepare region A and B

In [7]:
### init
vec_txt_cname_A = c("Chrom_A", "ChromStart_A", "ChromEnd_A", "Name")
vec_txt_cname_B = c("Chrom_B", "ChromStart_B", "ChromEnd_B", "Name")
vec_txt_cname   = c("Chrom",   "ChromStart",   "ChromEnd",   "Name", "Group", "Label")
txt_assay = TXT_ASSAY

### prepare point A
dat = dat_region_arrange
dat = dat %>% 
    dplyr::select(!!!vec_txt_cname_A) %>% 
    dplyr::mutate(
        Group = txt_assay,
        Label = "Loop_A"
    ) %>%
    dplyr::distinct()
colnames(dat) = vec_txt_cname
dat_region_A  = dat

### prepare point B
dat = dat_region_arrange
dat = dat %>% 
    dplyr::select(!!!vec_txt_cname_B)%>% 
    dplyr::mutate(
        Group = txt_assay,
        Label = "Loop_B"
    ) %>%
    dplyr::distinct()
colnames(dat) = vec_txt_cname
dat_region_B  = dat

In [8]:
dat = dat_region_A
fun_display_table(head(dat))

Chrom,ChromStart,ChromEnd,Name,Group,Label
chr10,72223000,72224000,chr10:72223000-72224000|chr10:72328000-72329000,hic_intact,Loop_A
chr10,64041000,64042000,chr10:64041000-64042000|chr10:67697000-67698000,hic_intact,Loop_A
chr10,78302000,78304000,chr10:78302000-78304000|chr10:79194000-79196000,hic_intact,Loop_A
chr10,13372000,13373000,chr10:13372000-13373000|chr10:13404000-13405000,hic_intact,Loop_A
chr10,132388000,132389000,chr10:132388000-132389000|chr10:132637000-132638000,hic_intact,Loop_A
chr10,114550000,114552000,chr10:114550000-114552000|chr10:114876000-114878000,hic_intact,Loop_A

In [9]:
dat = dat_region_B
fun_display_table(head(dat))

Chrom,ChromStart,ChromEnd,Name,Group,Label
chr10,72328000,72329000,chr10:72223000-72224000|chr10:72328000-72329000,hic_intact,Loop_B
chr10,67697000,67698000,chr10:64041000-64042000|chr10:67697000-67698000,hic_intact,Loop_B
chr10,79194000,79196000,chr10:78302000-78304000|chr10:79194000-79196000,hic_intact,Loop_B
chr10,13404000,13405000,chr10:13372000-13373000|chr10:13404000-13405000,hic_intact,Loop_B
chr10,132637000,132638000,chr10:132388000-132389000|chr10:132637000-132638000,hic_intact,Loop_B
chr10,114876000,114878000,chr10:114550000-114552000|chr10:114876000-114878000,hic_intact,Loop_B

## Save results

In [10]:
### set file path
txt_folder = TXT_FOLDER_REGION
txt_fdiry  = file.path(FD_RES, "region", txt_folder)
txt_fname = "K562.hg38.hic_intact.Loop_A.bed.gz"
txt_fpath = file.path(txt_fdiry, txt_fname)

### get table
dat = dat_region_A
dat = dat %>% dplyr::arrange(Chrom, ChromStart, ChromEnd)

### write tabel
dir.create(txt_fdiry, showWarnings = FALSE)
write_tsv(dat, txt_fpath, col_names = FALSE)

In [11]:
### set file path
txt_folder = TXT_FOLDER_REGION
txt_fdiry  = file.path(FD_RES, "region", txt_folder)
txt_fname = "K562.hg38.hic_intact.Loop_B.bed.gz"
txt_fpath = file.path(txt_fdiry, txt_fname)

### get table
dat = dat_region_B
dat = dat %>% dplyr::arrange(Chrom, ChromStart, ChromEnd)

### write tabel
dir.create(txt_fdiry, showWarnings = FALSE)
write_tsv(dat, txt_fpath, col_names = FALSE)

In [12]:
### set file path
txt_folder = TXT_FOLDER_REGION
txt_fdiry  = file.path(FD_RES, "region", txt_folder, "summary")
txt_fname = "K562.hg38.hic_intact.Loop.tsv"
txt_fpath = file.path(txt_fdiry, txt_fname)

### get table
dat = dat_region_arrange
dat = dat %>% dplyr::arrange(
    Chrom_A, ChromStart_A, ChromEnd_A,
    Chrom_B, ChromStart_B, ChromEnd_B
)

### write tabel
dir.create(txt_fdiry, showWarnings = FALSE)
write_tsv(dat, txt_fpath)